#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+SINGLE_CORE\
     +define+ST_WIDTH_32\
     +define+ST32_RANDOM_TEST_32X16\
     -f ../filelist/filelist_st32.f  
     #+define+ST32_RANDOM_TEST_32X8\
     #+define+ST32_RANDOM_TEST_48X8\
     #+define+ST32_RANDOM_TEST_64X8\

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.tsqr_mc_st32_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/tile_no    

add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/tsqr_fi       

add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/hh_din
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d1_rdy
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d1
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d1_vld
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d2_rdy
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d2
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/u_sqrt/io_in_a
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/u_sqrt/io_out_s
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d2_vld
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/vk1_rdy
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/vk1
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/vk1_vld
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d3_rdy
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d3
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d3_vld
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/tk_rdy
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/tk
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/tk_vld
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d4_rdy
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d4
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d4_vld
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d5_rdy
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d5
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d5_vld
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/yjp_rdy
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/hh_dout
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/yjp_vld
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/d4_sft
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_fsm/yj_sft
add wave -position insertpoint /tsqr_mc_st32_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/hh_din

add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st32_tb/u_tsqr_mc/c1_rtri_mem_doutb

#run 2 us                                                                            
run 2000 us                                                                            

